spring:
  datasource:
    url: jdbc:postgresql://learningsquaredatabase.cvw2y2ky8frg.eu-north-1.rds.amazonaws.com:5432/LearningSquareDatabase
    username: postgres
    password: learningsquarepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
